<a href="https://colab.research.google.com/github/qasraposas01-alt/CPE-311/blob/main/Midterm_Skills_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display
import io

upload = widgets.FileUpload(
    accept='.csv,.json',
    multiple=True
)

display(upload)

FileUpload(value={}, accept='.csv,.json', description='Upload', multiple=True)

In [11]:
sales_data = None
customer_data = None

for filename, file_info in upload.value.items():

    if filename.endswith('.csv'):
        sales_data = pd.read_csv(io.BytesIO(file_info['content']))
        print("Sales data loaded")
        display(sales_data.head())

    elif filename.endswith('.json'):
        customer_data = pd.read_json(io.BytesIO(file_info['content']))
        print("Customer data loaded")
        display(customer_data.head())

Customer data loaded

  CustomerID     Name    JoinDate
0       C001    Alice  2022-12-01
1       C002      Bob  2022-11-15
2       C003  Charlie  2023-01-05
3       C004    Diana  2023-01-10
4       C005     Evan  2023-01-20

Sales data loaded

  TransactionID CustomerID TransactionDate Product  Quantity  Price  Discount
0          T001       C001      2023-01-01  Widget         2     10      0.00
1          T002       C002      2023-01-05  Gadget         1     20      0.10
2          T003       C003      2023-01-07  Widget         3     10      0.00
3          T004       C002      2023-01-10   Gizmo         5     15      0.05
4          T005       C001      2023-01-12  Widget         1     10      0.00